stages:
  - deploy

staging:
  stage: deploy
  script:
    - gem install faraday -v 1.8.0
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_STAGING_APP_NAME --api_key=$HEROKU_API_KEY
  only:
    - development